# Generated by Django 5.0.7 on 2025-08-05 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def create_initial_langs(apps, schema_editor):
    # Get the historical version of the 'Category' model
    Lang = apps.get_model('teacore', 'Lang') 
    
    languages = [
            {"code": "es", "name": "Español"},
            {"code": "en", "name": "English"},
            {"code": "fr", "name": "Français"},
            {"code": "pt", "name": "Português"},
            {"code": "de", "name": "Deutsch"},
            {"code": "it", "name": "Italiano"},
        ]

    for index, lang_data in enumerate(languages, start=1):
        lang, _ = Lang.objects.get_or_create(code=lang_data["code"])
        lang.name = lang_data["name"]
        lang.is_default = lang.code == "es"
        lang.is_enabled = lang.code == "es"
        lang.save()

def reverse_create_initial_langs(apps, schema_editor):
    # Optional: Logic to reverse the data insertion when un-applying the migration
    Lang = apps.get_model('teacore', 'Lang')
    Lang.objects.filter(code__in=['es','en','fr','pt','de','it']).delete()

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=2, unique=True)),
                (
                    "name",
                    models.CharField(
                        editable=False,
                        help_text="Use only endonym (the country name in his own languaje)",
                        max_length=64,
                    ),
                ),
                ("is_default", models.BooleanField(default=False, editable=False)),
                ("is_enabled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254, unique=True)),
                ("opt_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MailBlackListed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient", models.EmailField(max_length=254)),
                ("request", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MailBlackListRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=192, unique=True)),
                ("is_enabled", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MailSent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=64)),
                ("subject", models.CharField(max_length=192)),
                ("template", models.CharField(max_length=96)),
                ("sender", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent",
                        to="teacore.mail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailsent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64)),
                ("body", models.TextField()),
                ("is_published", models.BooleanField(default=False)),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teacore.lang"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="widget",
            constraint=models.UniqueConstraint(
                fields=("slug", "lang"), name="widget_unique_slug_lang"
            ),
        ),
        migrations.CreateModel(
            name="MediaManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Manager",
                "verbose_name_plural": "Media Manager",
            },
        ),

        migrations.RunPython(create_initial_langs, reverse_code=reverse_create_initial_langs),
    ]
