# Generated by Django 5.2.13 on 2026-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacore", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailblacklisted",
            old_name="is_active",
            new_name="is_enabled",
        ),
        migrations.RenameField(
            model_name="widget",
            old_name="is_active",
            new_name="is_enabled",
        ),
        migrations.RemoveField(
            model_name="mailblacklistrule",
            name="is_active",
        ),
        migrations.AddField(
            model_name="mailblacklisted",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mailblacklistrule",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
