# Generated by Django 6.0.6 on 2026-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacore", "0002_rename_is_active_mailblacklisted_is_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        help_text="Código ISO 3166 A-2",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        editable=False, help_text="Nombre del país", max_length=96
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AlterField(
            model_name="lang",
            name="name",
            field=models.CharField(
                editable=False,
                help_text="Utiliza el endónimo (el nombre del país en su propio idioma).",
                max_length=64,
            ),
        ),
    ]
