# Generated by Django 6.0.7 on 2026-07-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacore", "0003_country_alter_lang_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "País", "verbose_name_plural": "Países"},
        ),
        migrations.AlterModelOptions(
            name="lang",
            options={"verbose_name": "Idioma", "verbose_name_plural": "Idiomas"},
        ),
        migrations.AddField(
            model_name="country",
            name="is_default",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="country",
            name="is_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
